api:
  api_token: ragforge-dmZWY4NTZhNmQxNDExZjBiOTY5NGE5MG
  auth_token: ImRhZWVjMzc2NmQxMDExZjBhOGQwNGE5MGIyNjUyM2QxIg.aInFxg.opxsgsRJBrwcpfFozQKc3P703dA
  base_url: http://127.0.0.1:9380
  headers:
    Accept: application/json
    Content-Type: application/json
  timeout: 30
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
output:
  format: table
  max_width: 120
