api:
  api_token: ragforge-IxZTA5YTBlNzY5MjExZjA4ZDdmNGE5MG
  auth_token: ImEwY2VmY2E0NmRlNDExZjA4MzhlNGE5MGIyNjUyM2QxIg.aJmyBQ.EDL4fDxuLN6PiVQ1julRPmeXJbs
  base_url: http://127.0.0.1:9380
  headers:
    Accept: application/json
    Content-Type: application/json
  timeout: 30
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
output:
  format: table
  max_width: 120
